mv_ddr: fix indentation causing compilation error
This patch fixes code indentation in ddr3_training_leveling.c file
causing compilation error with gcc 6.3.

Change-Id: Ic1d05fa61942a219f349af1e57db7376ce4df1f7
Signed-off-by: Victor Axelrod <victora@marvell.com>
Reported-by: Konstantin Porotchkin <kostap@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/44921