mv_ddr4_mpr_pda_if.c: avoid -Werror=parentheses
Building fails with:
mv_ddr4_mpr_pda_if.c: In function ‘mv_ddr4_pda_pattern_odpg_load’:
mv_ddr4_mpr_pda_if.c:708:5: error: suggest explicit braces to
avoid ambiguous ‘else’ [-Werror=parentheses]
  if (subphy_mask != 0xf)

This patch adds the missing braces.

Signed-off-by: Heinrich Schuchardt <xypron.glpk@gmx.de>