mv_ddr: replace preprocessor errors with info messages
This patch turns preprocessor errors to info messages to prevent corresponding
compilation failures. The conditional compilation errors were introduced by
the patch revising and fixing tip pad inversion function to catch missing or
incorrect platform definition. Need to move this to per platform code.

Change-Id: I769c403a45621f469608c4d491b80a8ec8465d7c
Signed-off-by: Victor Axelrod <victora@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/45706